# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsBoom' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'SCLAlertView'
  pod 'NotificationBannerSwift', '2.0.1'
  # Pods for NewsBoom

end
